# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: balance.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'balance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbalance.proto\"S\n\x14UpdateBalanceRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x16\n\x0e\x63urrent_change\x18\x02 \x01(\x02\x12\x12\n\nmax_change\x18\x03 \x01(\x02\"?\n\x0f\x42\x61lanceResponse\x12\x17\n\x0f\x63urrent_balance\x18\x01 \x01(\x02\x12\x13\n\x0bmax_balance\x18\x02 \x01(\x02\"9\n\x16OpenTransactionRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x02\"D\n\x13TransactionResponse\x12\x16\n\x0etransaction_id\x18\x01 \x01(\x05\x12\x15\n\rlocked_amount\x18\x02 \x01(\x02\",\n\x12TransactionRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\x05\"#\n\x11TransactionStatus\x12\x0e\n\x06status\x18\x01 \x01(\t2\x88\x02\n\x0e\x42\x61lanceService\x12\x38\n\rUpdateBalance\x12\x15.UpdateBalanceRequest\x1a\x10.BalanceResponse\x12@\n\x0fOpenTransaction\x12\x17.OpenTransactionRequest\x1a\x14.TransactionResponse\x12<\n\x11\x43ommitTransaction\x12\x13.TransactionRequest\x1a\x12.TransactionStatus\x12<\n\x11\x43\x61ncelTransaction\x12\x13.TransactionRequest\x1a\x12.TransactionStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'balance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPDATEBALANCEREQUEST']._serialized_start=17
  _globals['_UPDATEBALANCEREQUEST']._serialized_end=100
  _globals['_BALANCERESPONSE']._serialized_start=102
  _globals['_BALANCERESPONSE']._serialized_end=165
  _globals['_OPENTRANSACTIONREQUEST']._serialized_start=167
  _globals['_OPENTRANSACTIONREQUEST']._serialized_end=224
  _globals['_TRANSACTIONRESPONSE']._serialized_start=226
  _globals['_TRANSACTIONRESPONSE']._serialized_end=294
  _globals['_TRANSACTIONREQUEST']._serialized_start=296
  _globals['_TRANSACTIONREQUEST']._serialized_end=340
  _globals['_TRANSACTIONSTATUS']._serialized_start=342
  _globals['_TRANSACTIONSTATUS']._serialized_end=377
  _globals['_BALANCESERVICE']._serialized_start=380
  _globals['_BALANCESERVICE']._serialized_end=644
# @@protoc_insertion_point(module_scope)
